---
- name: Ensure required repos are installed
  include_tasks: repos.yml
  tags: repos

- name: Update all packages and reboot
  include_tasks: update.yml
  tags: update

- name: Ensure required packages are installed
  include_tasks: packages.yml
  tags: packages

- name: Ensure certs are properly installed
  include_tasks: certs.yml
  tags: certs

- name: Ensure OpenShift installation is properly configured
  include_tasks: openshift.yml
  tags: openshift
