---
- name: Ensure required packages are installed
  become: True
  yum:
    name: "{{ yum_packages }}"
    state: present
    enablerepo: "epel"

- name: Install Ansible 2.9
  become: True
  pip:
    name: ansible
    version: 2.9.4
