azure:
  location: "East US"
  resource_group: "openshift6"
  image_publisher: "OpenLogic"
  image_offer: "CentOS"
  image_sku: "7.5"
  image_version: "latest"

openshift:
  master_nodes: [1,2,3]
  master_size: "Standard_B2s"
  infra_nodes: [1,2]
  infra_size: "Standard_B2ms"
  app_nodes: [1,2]
  app_size: "Standard_B2s"
  bastion_size: "Standard_B2ms"
  os_user: "openshift"
  admin_domain: "ocp-adm.mydomain.com"
  router_domain: "ocp.mydomain.com"
