---
- name: Ensure EPEL repo is installed
  include_tasks: epel.yml
  tags: epel_repo

- name: Update all packages and reboot
  include_tasks: update.yml
  tags: update

- name: Ensure required packages are installed
  include_tasks: packages.yml
  tags: packages

- name: Ensure Docker is properly installed
  include_tasks: docker.yml
  tags: docker

- name: Ensure Network is properly configured
  include_tasks: network.yml
  tags: network
